name: PayID Action

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master


jobs:
  pay:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code  
      uses: actions/checkout@v2

    - name: Checkout prior code  
      uses: actions/checkout@v2
      ref: HEAD^1
      path: .old-code

    - name: Checkout current code  
      uses: actions/checkout@v2
      ref: HEAD
      path: .new-code

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    
    - name: get commit message
      run: |
        echo ::set-env name=commitmsg::$(git log --format=%B -n 1 ${{ github.event.after }})

    - name: show commit message
      run : echo $commitmsg

    - name: Run PayID
      env:
        PAYID_WALLET_SECRET: ${{ secrets.PAYID_WALLET_SECRET }}
        changed_files: ${{ steps.file_changes.outputs.files_modified }}
        added_files: ${{ steps.file_changes.outputs.files_added }}
      run: |
        python pay_contributor.py
        